name: Run Maven Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '17'

        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                  ${{ runner.os }}-maven-

        - name: Install dependencies
          run: mvn install -DskipTests --file estacionamento/pom.xml

        - name: Run tests
          run: mvn test --file estacionamento/pom.xml
          working-directory: estacionamento